### ISSUE TITLE
Linker error - framework AudioUnit not found

### ISSUE THREAD

**Issue by henrinormak** [thermodo/ThermodoSDK#8]
When using the cocoapod for the SDK there is a linker error

```
ld: framework not found AudioUnit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This occurs on a blank project with ThermodoSDK as the only pod, but also on more complex projects.

Expected - either this is fixed or the installation guide is improved (in case there was a step other than linking to the pod needed).

Attaching a minimal project exhibiting said error.
http://cl.ly/3V3x1O381T3N

**Comment by henrinormak** [comment]
Replacing `AudioUnit` with `CoreAudio` in the podspec gets rid of the linker error. I assume using AudioUnit is producing a similar error as described in this SO post - http://stackoverflow.com/questions/1756212/framework-not-found-audiounit

**Comment by ksmandersen** [comment]
Sorry for the wait. I updated the podspec and it should work now. Still waiting for CocoaPods to merge the PR. Until then you can add ThermodoSDK like this:

```
pod 'ThermodoSDK', :git => 'https://github.com/thermodo/ThermodoSDK-iOS.git'
```

**Comment by henrinormak** [comment]
That does not actually fix the issue, because the podspec in the repo is still incorrect (i.e not matching the one you have put into the Specs repo). Anyway, should be a minor fix, thanks for the help!

**Comment by ksmandersen** [comment]
Whoops! Should be there now
